### ISSUE TITLE
[BUG] [Realme GT 2] Once screen is turned off, touch screen stops working.

### ISSUE THREAD

**Issue by Kingsman44** [QRD-Development/twrp_device_qcom_lahaina#1]
Device: Real Me GT 2
Android Rom: AOSPA
Android Version: 13
Version Used: 20231118 (As Boot header version is v3)

Logs grabbed from adb after screen turned off.
[loggg.txt](https://github.com/QRD-Development/twrp_device_qcom_lahaina/files/13657447/loggg.txt)

**Comment by snnbyyds** [comment]
> Device: Real Me GT 2 Android Rom: AOSPA Android Version: 13 Version Used: 20231118 (As Boot header version is v3)
> 
> Logs grabbed from adb after screen turned off. [loggg.txt](https://github.com/QRD-Development/twrp_device_qcom_lahaina/files/13657447/loggg.txt)

Sorry, this tree is only for QRD8350. It is not a common version for sm8350 devices and is device-specific.

**Comment by Kingsman44** [comment]
sorry about that, I didn't notice anyway. Thanks for your work. otherwise it works great in my device.
